# Generated by Django 5.0.4 on 2024-04-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=200, verbose_name='RA Aluno')),
                ('reader_name', models.CharField(max_length=200, verbose_name='Nome do Aluno')),
                ('reader_contact', models.CharField(max_length=200, verbose_name='Contato do Aluno')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Leitor',
                'verbose_name_plural': 'Leitores',
            },
        ),
    ]
