# Generated by Django 5.0.4 on 2024-04-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='grade_year',
            field=models.CharField(default='Desconhecido', max_length=50, verbose_name='Ano de Ensino'),
        ),
    ]
