# Generated by Django 5.0.4 on 2024-04-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0004_alter_reader_grade_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200, verbose_name='Nome do Livro')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN')),
                ('borrowed', models.BooleanField(default=False, verbose_name='Emprestado')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
