# Generated by Django 5.0.4 on 2024-04-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0008_loan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
