# Generated by Django 5.0.4 on 2024-04-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0002_reader_grade_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='grade_year',
            field=models.CharField(max_length=50, verbose_name='Ano de Ensino'),
        ),
    ]
